#!/usr/bin/python
import sys, glob
from bft2f_pb2 import *
sys.path.append('gen-py')
from user_base import get_client
from argparse import ArgumentParser
from Crypto.PublicKey import RSA 
from Crypto.Signature import PKCS1_v1_5

parser = ArgumentParser()
parser.add_argument('--client_id', '-cid',
                    type=str,
                    default='c0',
                    required=False)
parser.add_argument('--user_id', '-u',
                    type=str,
                    required=True)
parser.add_argument('--passphrase', '-p',
                    type=str,
                    required=True)
args = parser.parse_args()


client, t = get_client(args.client_id)
key = RSA.generate(2048)
signer1 = PKCS1_v1_5.new(key)
pub_key = key.publickey().exportKey('PEM')
priv_key_enc = key.exportKey('PEM', passphrase=args.passphrase)
rmsg = client.sign_up(user_id=args.user_id, user_pub_key=pub_key, user_priv_key_enc=priv_key_enc)
print rmsg
t.close()


